### ISSUE TITLE
Conditional Dialogue Nodes

### ISSUE THREAD

**Issue by wubbadukky** [ubco-video-game-development-club/rpg#56]
If we could have something reminiscent of an if statement for when dialogue nodes are called that would be super fresh.

**Comment by JadenBalogh** [comment]
I was thinking more about this problem today. What do you think about this solution @wubbadukky?

We make each NPC have a *list* of dialogue trees, rather than the current single option. You can add as many as you want in the inspector using this list, unique for every NPC. Each dialogue tree is referenced by an index based on its position in the list. Then, in the dialogue graph editor, you would be able to add an optional setting in each node to change the currently active dialogue tree.

So, for example, in the last node of a dialogue tree, you could set it to change the currently active dialogue tree to index 1 instead of index 0. From then on, until this index was changed again, that NPC would play dialogue tree 1 instead of the initial dialogue tree 0. So, the second one could be something like "Why are you still talking to me? Go do your task!" for example.

Would that be a good solution to this problem?

**Comment by wubbadukky** [comment]
I think that would be a great way of handling it @JadenBalogh .

**Comment by JadenBalogh** [comment]
On it!

**Comment by JadenBalogh** [comment]
Added a separate issue for the task of adding/removing specific conversation options based on conditions like alignment thresholds #61.
